export { createPlatform } from "./platform.js";
export { createPlatformConfig, STANDARD_NAVIGATION } from "./core/config/platform-config.js";
export { createSupabaseClient } from "./core/api/supabase-client.js";
export { createLearnerApi } from "./core/api/learner-api.js";
export { createAuthService } from "./core/auth/auth-service.js";
export { createSessionService } from "./core/session/session-service.js";
export { createLearnerContext } from "./core/learner/learner-context.js";
export { createOnboardingService } from "./core/onboarding/onboarding-service.js";
export { createProfileService } from "./core/profile/profile-service.js";
export { createEnrolmentService } from "./core/enrolment/enrolment-service.js";
export { createAssignmentService } from "./core/assignment/assignment-service.js";
export { createProgressService } from "./core/progress/progress-service.js";
export { createSubmissionService, assertSecureSubmission } from "./core/submission/submission-service.js";
export { evidence, EVIDENCE_TYPES, toApiResponse } from "./core/evidence/evidence.js";
export { createPlatformState, derivePlatformState, PLATFORM_STATES } from "./core/state/platform-state.js";
export { PlatformError, mapPlatformError, ERROR_CATEGORIES } from "./core/errors/platform-error.js";
export { createLogger, redact } from "./core/logging/logger.js";
export { createFeatureFlags } from "./core/feature-flags/feature-flags.js";
export { createThemeService, applyBranding, THEME_MODES, THEME_EVENT } from "./theme/theme.js";
export { createLearnerHeader } from "./ui/learner-header/learner-header.js";
export { createNavigationShell } from "./ui/navigation/navigation-shell.js";
export { createAccountDialog } from "./ui/account/account-dialog.js";
export { createOnboardingView } from "./ui/onboarding/onboarding-view.js";
export { createModal } from "./ui/modal/modal.js";
export { createToastRegion } from "./ui/notifications/toast.js";
export { createLoadingState } from "./ui/loading/loading-state.js";
export { createErrorBanner } from "./ui/errors/error-banner.js";
export { createProgressCard } from "./ui/progress-card/progress-card.js";
export { createActivityCard } from "./ui/activity-card/activity-card.js";
export { createEmptyState } from "./ui/empty-state/empty-state.js";
export { runConformanceChecks, assertConformant } from "./conformance/index.js";
